# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bank.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(657, 528)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.selectAcc = QtWidgets.QComboBox(self.centralwidget)
        self.selectAcc.setObjectName("selectAcc")
        self.verticalLayout_3.addWidget(self.selectAcc)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.spinDep = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.spinDep.setFont(font)
        self.spinDep.setObjectName("spinDep")
        self.verticalLayout.addWidget(self.spinDep)
        self.pushDep = QtWidgets.QPushButton(self.centralwidget)
        self.pushDep.setMinimumSize(QtCore.QSize(0, 50))
        self.pushDep.setObjectName("pushDep")
        self.verticalLayout.addWidget(self.pushDep)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.spinWith = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.spinWith.setFont(font)
        self.spinWith.setObjectName("spinWith")
        self.verticalLayout_2.addWidget(self.spinWith)
        self.pushWith = QtWidgets.QPushButton(self.centralwidget)
        self.pushWith.setMinimumSize(QtCore.QSize(0, 50))
        self.pushWith.setObjectName("pushWith")
        self.verticalLayout_2.addWidget(self.pushWith)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushDep.setText(_translate("MainWindow", "Депозит"))
        self.pushWith.setText(_translate("MainWindow", "Вывод"))
