# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gibdd.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(657, 528)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.selectVehicle = QtWidgets.QComboBox(self.centralwidget)
        self.selectVehicle.setObjectName("selectVehicle")
        self.verticalLayout_3.addWidget(self.selectVehicle)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.spinRide = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.spinRide.setFont(font)
        self.spinRide.setMaximum(10000000)
        self.spinRide.setObjectName("spinRide")
        self.verticalLayout.addWidget(self.spinRide)
        self.pushRide = QtWidgets.QPushButton(self.centralwidget)
        self.pushRide.setMinimumSize(QtCore.QSize(0, 50))
        self.pushRide.setStyleSheet("background-color: rgb(234, 156, 0);")
        self.pushRide.setObjectName("pushRide")
        self.verticalLayout.addWidget(self.pushRide)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushGas = QtWidgets.QPushButton(self.centralwidget)
        self.pushGas.setMinimumSize(QtCore.QSize(0, 50))
        self.pushGas.setStyleSheet("background-color: rgb(118, 0, 177)")
        self.pushGas.setObjectName("pushGas")
        self.verticalLayout_2.addWidget(self.pushGas)
        self.pushTier = QtWidgets.QPushButton(self.centralwidget)
        self.pushTier.setMinimumSize(QtCore.QSize(0, 50))
        self.pushTier.setStyleSheet("background-color: rgb(85, 85, 127)")
        self.pushTier.setObjectName("pushTier")
        self.verticalLayout_2.addWidget(self.pushTier)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushRide.setText(_translate("MainWindow", "Ехать"))
        self.pushGas.setText(_translate("MainWindow", "Заправка"))
        self.pushTier.setText(_translate("MainWindow", "Шиномонтаж"))
